### ISSUE TITLE
Adding a build system

### ISSUE THREAD

**Issue by rekado** [sjm-tl-gh/inspekt3d#1]
Hi,

inspekt3d looks very promising!  Thank you for working on it.

I would like to package this for GNU Guix.  Would you be willing to accept patches that add a build system e.g. with autotools?

**Comment by sjm-tl-gh** [comment]
Hi rekado,

Yes, patches for an autotools build system would be welcome.  You can do it as a Git PR, if that's convenient.  Thanks for your interest in this project!

**Comment by sjm-tl-gh** [comment]
I added a simple autotools build system.  If you need any changes to the build system for Guix, let me know, or submit a PR.

**Comment by rekado** [comment]
Thank you.

The configure script currently doesn't check for dependencies, and the Makefile does not cause the Scheme files to be compiled.

I tried compiling the source files, but unfortunately I get `unbound variable <shape>` when trying to compile `viewer.scm`.

Attached are my changes to the build system.
[0001-WIP-build-system.patch.txt](https://github.com/sjm-tl-gh/inspekt3d/files/2376128/0001-WIP-build-system.patch.txt)

**Comment by sjm-tl-gh** [comment]
Thanks for the patch.

Re: ```unbound variable <shape>```, make sure you have the latest commit of the libfive master branch.  I did a libfive PR that (hopefully) fixes this for you:

https://github.com/libfive/libfive/pull/200

If it still doesn't work, let me know.

**Comment by sjm-tl-gh** [comment]
@rekado, your patch has been applied.  I had to make a few further changes to get it to work with Ubuntu 18.04's Guile packages.
